name: Test and Publish NPM Package

on:
  release:
    types: [created]

jobs:
#  test:
#    strategy:
#      matrix:
#        node-version: [14, 16, 18]
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: â¬‡ï¸ Checkout code
#        uses: actions/checkout@v2
#      - name: ğŸ“¦ Setup Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: ğŸ“¥ Install dependencies
#        run: npm ci
#      - name: ğŸƒ Run tests
#        run: npm test

  publish:
#    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v2
      - name: ğŸ“¦ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
#      - name: ğŸ“¥ Install dependencies and build
#        run: npm ci & npm run build
      - name: ğŸš€ Publish to NPM on prerelease
        if: github.event_name == 'prereleased'
        run: npm publish --tag pre
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ğŸš€ Publish to NPM on release
        if: github.event_name == 'released'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
